name: calcolapizza
description: Le esatte dosi per i tuoi impasti in pochi secondi

version: 1.2.0+9

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  animations: ^2.0.11
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8
  lottie: ^3.1.3
  another_flushbar: ^1.12.30
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  share_plus: ^12.0.0
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/no_data_pizza.flr
    - assets/lang/lang.json
